#!/bin/sh

##H Usage: manage ACTION [SECURITY-STRING]
##H
##H Available actions:
##H   help        show this help
##H   version     get current version of the service
##H   status      show current service's status
##H   sysboot     start server from crond if not running
##H   restart     (re)start the service
##H   start       (re)start the service
##H   graceful    restart the service gracefully
##H   stop        stop the service
##H
##H For more details please refer to:
##H   https://github.com/aurimasrep/PhEDExDashboards

if [ $(id -un)  = cmsweb ]; then
  echo "ERROR: please use another account" 1>&2
  exit 1
fi

echo_e=-e bsdstart=bsdstart
case $(uname) in Darwin )
  md5sum() { md5 -r ${1+"$@"}; }
  echo_e= bsdstart=start
  ;;
esac

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
CFGDIR=$(dirname $0)
LOGDIR=$TOP/logs/$ME
STATEDIR=$TOP/state/$ME
COLOR_OK="\\033[0;32m"
COLOR_WARN="\\033[0;31m"
COLOR_NORMAL="\\033[0;39m"

export PHEDEXDASHBOARDS_ROOT=/afs/cern.ch/user/a/arepecka/public/WebTest/PhEDExDashboards/
export PHEDEXDASHBOARDS_VERSION=v00.00.01

sysboot()
{
  dostart=false
  if [ $(pgrep -u $(id -u) -f "[/]wmarch" | wc -l) = 0 ]; then
      dostart=true
  fi
  $dostart && start
}

# Start the service.
start()
{
  cd $PHEDEXDASHBOARDS_ROOT
  echo "starting $ME"
  pm2 start ./process.yml
}

# Stop the service.
stop()
{
  cd $PHEDEXDASHBOARDS_ROOT
  echo "stopting $ME"
  pm2 stop ./process.yml
}

# Check if the server is running.
status()
{
  pm2 list
}

# Gracefully reloading
graceful()
{
  cd $PHEDEXDASHBOARDS_ROOT
  echo "restarting $ME gracefully"
  pm2 gracefulReload ./process.yml
}

# Verify the security string.
check()
{
  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
    echo "$0: cannot complete operation, please check documentation." 1>&2
    exit 2;
  fi
}

# Main routine, perform action requested on command line.
case ${1:-status} in
  sysboot )
    sysboot
    ;;

  start | restart )
    check
    stop
    start
    ;;

  status )
    status
    ;;

  stop )
    check
    stop
    ;;

  graceful )
    check
    graceful
    ;;

  help )
    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
    ;;

  version )
    echo "$PHEDEXDASHBOARDS_VERSION"
    ;;

  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1
    ;;
esac
